// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXaetL2R7rw0hrmNVyLWyPcXwcMqOoyg',
    appId: '1:344835605079:web:d85d02377ca6cb39e19912',
    messagingSenderId: '344835605079',
    projectId: 'easy-crm-756ad',
    authDomain: 'easy-crm-756ad.firebaseapp.com',
    storageBucket: 'easy-crm-756ad.firebasestorage.app',
    measurementId: 'G-41B0VK89XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysxlokB7AWxAht_e2Om4pPezK_2PcNVA',
    appId: '1:344835605079:android:214dfc2a50084089e19912',
    messagingSenderId: '344835605079',
    projectId: 'easy-crm-756ad',
    storageBucket: 'easy-crm-756ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOMagRasR4kgklUiZPWPg6hSbhZnrnro',
    appId: '1:344835605079:ios:99894c0bb2fbb79be19912',
    messagingSenderId: '344835605079',
    projectId: 'easy-crm-756ad',
    storageBucket: 'easy-crm-756ad.firebasestorage.app',
    iosBundleId: 'com.example.fullcommCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOMagRasR4kgklUiZPWPg6hSbhZnrnro',
    appId: '1:344835605079:ios:99894c0bb2fbb79be19912',
    messagingSenderId: '344835605079',
    projectId: 'easy-crm-756ad',
    storageBucket: 'easy-crm-756ad.firebasestorage.app',
    iosBundleId: 'com.example.fullcommCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXaetL2R7rw0hrmNVyLWyPcXwcMqOoyg',
    appId: '1:344835605079:web:1c974d9429573c64e19912',
    messagingSenderId: '344835605079',
    projectId: 'easy-crm-756ad',
    authDomain: 'easy-crm-756ad.firebaseapp.com',
    storageBucket: 'easy-crm-756ad.firebasestorage.app',
    measurementId: 'G-RVQC9RMNP9',
  );
}
